config:
  # List of additional directories to search for config and template files.
  additionalfiles: []

# These values define the schema and are NOT intended to be changed by end users.
template:
  # Valid types of devices.
  devicetype:
    - firewall
    - switch
    - api
    - dhcp
  # Valid replacement keys in commands.
  keys:
    - interface
    - ipaddress
    - vlanid
    - vlanname
    - zone
    - cidr
    - mask

# ---------------------------------------------------------------------------
# Vendor Sections
# use the section below to define custom devices, or vendors for commands to output.
#
# Each vendor definition contains:
#   - A devicetype (must match one of the template.devicetype items)
#   - A set of command groups, keyed by an item (e.g., interface, vlan, dhcprelay)
#   - CRUD-style operations within each group (create, read, update, delete)
#
# Rules:
#   - All CRUD operations must be arrays, even if only one command is defined.
#   - All placeholder keys (e.g., {{interface}}, {{vlanid}}) will be replaced
#     by the program at runtime with the coinciding input.
#   - Placeholder keys must be surrounded by double curly braces: {{key}}
#   - Command groups may only use the CRUD operation types:
#         create
#         read
#         update
#         delete
#
# Any additional operation types will be ignored or result in validation failure.
# ---------------------------------------------------------------------------


paloalto:
  devicetype: firewall
  commands:
    interface:
      create:
        - set network interface aggregate-ethernet {{interface}} layer3 ip {{ipaddress}} vlan {{vlanid}}
        - set network interface aggregate-ethernet {{interface}} description {{vlanname}}
        - set zone {{zone}} network layer3 {{interface}}
      update:
        - set network interface aggregate-ethernet {{interface}} layer3 ip {{ipaddress}} vlan {{vlanid}}
        - set network interface aggregate-ethernet {{interface}} description {{vlanname}}
        - set zone {{zone}} network layer3 {{interface}}
    dhcprelay:
      create: []

cisco:
  devicetype: switch
  commands:
    vlan:
      create:
        - vlan {{vlanid}}
        - name {{vlanname}}
      read:
        - show vlan id {{vlanid}}
      update:
        - vlan {{vlanid}}
        - name {{vlanname}}
      delete:
        - no vlan {{vlanid}}
